const templates=[
["Elegant Gold","traditional","gold"],["Modern Rose","modern","rose"],["Royal Blue","royal","blue"],["Sage Garden","floral","green"],["Lavender Love","floral","purple"],["Sunset Marigold","floral","orange"],["Classic Cream","traditional","cream"],["Red Heritage","traditional","red"],["Minimal Pearl","modern","cream"],["Midnight Royal","royal","blue"],["Blush Bloom","floral","rose"],["Temple Gold","traditional","gold"],["Emerald Grace","royal","green"],["Dusty Rose","modern","rose"],["Regal Navy","royal","blue"],["Peach Petals","floral","orange"],["Vintage Ivory","traditional","cream"],["Plum Elegance","royal","purple"],["Garden Sage","floral","green"],["Ruby Classic","traditional","red"]
];
let selected=0;
const $=id=>document.getElementById(id);
function artClass(i){return ["gold","rose","blue","green","purple","orange","cream","red"][i%8]}
function renderTemplates(filter="all"){
 const grid=$("templateGrid");grid.innerHTML="";
 templates.forEach((t,i)=>{if(filter!=="all"&&t[1]!==filter)return;
 const card=document.createElement("div");card.className="template-card";card.innerHTML=`<div class="template-art ${artClass(i)}"><div class="tp"></div><div class="tt">${t[0]}</div><div class="tl"></div><div class="lines"></div></div><footer><b>${t[0]}</b><small>${t[1][0].toUpperCase()+t[1].slice(1)} • ${i<6?"Free":"Premium"}</small></footer>`;
 card.onclick=()=>selectTemplate(templates.indexOf(t));grid.appendChild(card)});
}
function renderMini(){const el=$("miniTemplates");el.innerHTML=templates.slice(0,8).map((t,i)=>`<button class="mini ${i===selected?'active':''}" data-i="${i}">${t[0]}</button>`).join("");el.querySelectorAll(".mini").forEach(b=>b.onclick=()=>selectTemplate(+b.dataset.i))}
function selectTemplate(i){selected=i;$("selectedName").textContent=templates[i][0];renderMini();$("preview").className="bio-preview design-"+((i%3)+1);updatePreview()}
function updatePreview(){
 const val=id=>$(id).value||"—";
 $("preview").innerHTML=`<div class="bio-top">॥ श्री गणेशाय नमः ॥</div><div class="bio-person"><div><small>MARRIAGE BIODATA</small><h2>${val("name")}</h2><p>${val("profession")}</p></div><div class="profile"><img id="pimg"><span id="ph">PHOTO</span></div></div><hr><h5>PERSONAL DETAILS</h5><div class="bio-details"><div>Date of Birth <b>${val("dob")}</b></div><div>Height <b>${val("height")}</b></div><div>Religion <b>${val("religion")}</b></div><div>Education <b>${val("education")}</b></div><div>Caste <b>${val("caste")}</b></div><div>Company <b>${val("company")}</b></div></div><h5>FAMILY DETAILS</h5><div class="bio-details"><div>Father <b>${val("father")}</b></div><div>Mother <b>${val("mother")}</b></div></div><h5>ABOUT ME</h5><p class="bio-about">${val("about")}</p><div class="bio-foot">📞 ${val("phone")} &nbsp; • &nbsp; 📍 ${val("city")}</div>`;
 const saved=document.getElementById("pimg"); if(window.profileURL){saved.src=window.profileURL;saved.style.display="block";$("ph").style.display="none";}
}
["name","dob","height","religion","caste","education","profession","company","father","mother","city","phone","about"].forEach(id=>$(id).addEventListener("input",()=>{localStorage.setItem("vivah_"+id,$(id).value);updatePreview()}));
$("photo").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;window.profileURL=URL.createObjectURL(f);updatePreview()});
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTemplates(b.dataset.filter)});
$("pdfBtn").onclick=()=>{localStorage.setItem("vivah_downloads",+(localStorage.getItem("vivah_downloads")||0)+1);window.print()};
$("jpgBtn").onclick=async()=>{await downloadJpg();localStorage.setItem("vivah_downloads",+(localStorage.getItem("vivah_downloads")||0)+1)};
$("payBtn").onclick=()=>toast("Demo checkout: connect Razorpay server credentials to accept real payments.");
$("langBtn").onclick=()=>{const h=document.documentElement;const hindi=h.lang!=="hi";h.lang=hindi?"hi":"en";$("langBtn").textContent=hindi?"English":"हिंदी";document.querySelectorAll("[data-i18n]").forEach(e=>{const k=e.dataset.i18n;e.textContent=hindi?({templates:"टेम्पलेट",how:"कैसे काम करता है",create:"बायोडाटा बनाएं",start:"शुरू करें",eyebrow:"भारत का बायोडाटा मेकर",heroTitle:"आपकी कहानी एक खूबसूरत बायोडाटा की हकदार है।",heroText:"डिज़ाइन चुनें, जानकारी और फोटो जोड़ें और सुंदर बायोडाटा डाउनलोड करें।",browse:"टेम्पलेट देखें →",make:"मेरा बनाएं",templateTitle:"अपनी पसंद की शैली चुनें।",templateText:"पारंपरिक, मॉडर्न, फ्लोरल और रॉयल डिज़ाइन।",howTitle:"खाली पेज से सुंदर बायोडाटा तक।",makerTitle:"कुछ ही मिनटों में बनाएं।"}[k]||e.textContent):({templates:"Templates",how:"How it works",create:"Create Biodata",start:"Start Free",eyebrow:"INDIA'S BIODATA MAKER",heroTitle:"Your story deserves a beautiful biodata.",heroText:"Choose a design, add your details and photo, then download a polished marriage biodata ready to share.",browse:"Browse Templates →",make:"Make Mine Free",templateTitle:"Find a style that feels like you.",templateText:"Traditional, modern, floral and royal designs — built for Indian marriage biodatas.",howTitle:"From blank page to beautiful biodata.",makerTitle:"Create yours in minutes."}[k]||e.textContent)});};
function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2600)}
async function downloadJpg(){
 const p=$("preview"),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=1200;canvas.height=1600;ctx.fillStyle="#fff";ctx.fillRect(0,0,1200,1600);ctx.fillStyle="#7b2036";ctx.font="bold 30px Arial";ctx.fillText("VIVAHBIO — MARRIAGE BIODATA",70,80);ctx.fillStyle="#333";ctx.font="24px Arial";
 const text=[["Name", $("name").value],["Date of Birth",$("dob").value],["Height",$("height").value],["Religion",$("religion").value],["Education",$("education").value],["Profession",$("profession").value],["Company",$("company").value],["Father",$("father").value],["Mother",$("mother").value],["City",$("city").value],["Phone",$("phone").value]];
 let y=150;text.forEach(([a,b])=>{ctx.fillStyle="#777";ctx.fillText(a,80,y);ctx.fillStyle="#222";ctx.fillText(b||"—",330,y);y+=58});ctx.fillStyle="#7b2036";ctx.font="bold 25px Arial";ctx.fillText("About Me",80,y+25);ctx.fillStyle="#444";ctx.font="20px Arial";wrap(ctx,$("about").value||"—",80,y+70,1040,30);const a=document.createElement("a");a.download="marriage-biodata.jpg";a.href=canvas.toDataURL("image/jpeg",.92);a.click();
}
function wrap(ctx,text,x,y,max,lh){let words=text.split(" "),line="";for(const w of words){let test=line+w+" ";if(ctx.measureText(test).width>max){ctx.fillText(line,x,y);line=w+" ";y+=lh}else line=test}ctx.fillText(line,x,y)}
templates.forEach((_,i)=>{});renderTemplates();renderMini();Object.keys(localStorage).filter(k=>k.startsWith("vivah_")).forEach(k=>{const id=k.replace("vivah_","");if($(id))$(id).value=localStorage.getItem(k)});updatePreview();
